export const CONSTANTS = {
    URL_API_EXPRESS: "https://outstanding-yew-386004.uc.r.appspot.com/",
    HOME_INTRO_TEXT: "El profesor Charles quiere reclutarte, únete a la lucha contra los Centinelas.",
    FORM_INTRO_TITLE: "Evaluador de ADN",
    FORM_INTRO_TEXT: "Ingresa tu secuencia ADN, teniendo en cuenta las siguientes recomendaciones:",
    FORM_INTRO_DESC_A: "(1) Escribe cada fila seperada por coma",
    FORM_INTRO_DESC_B: "(2) La matriz debe ser mínimo de tamaño 4x4 y simétrica",
    FORM_INTRO_DESC_C: "(3) Solo se permiten las letras A, T, C, G",
    FORM_INTRO_DESC_D: "Ejemplo: ATGC,CAGT,TTAT,AAGG",
    FORM_MODAL_TITLE: "Tu secuencia de ADN indica que eres:",
    FORM_MODAL_HUMAN: "HUMANO",
    FORM_MODAL_MUNTANT: "MUTANTE",
    FORM_MODAL_ADN: "Este ADN ya fue analizado y registrado, ingresa uno diferente",
    FORM_MODAL_ERROR: "Tu secuencia de ADN no cumple la longitud mínima",
    STATS_INTRO_TITLE: "Estadísticas de evaluados",
    BUTTON_INSERT_DNA: "Validar ADN",
    BUTTON_STATS: "Estadísticas",
    BUTTON_BACK: "Volver",
    BUTTON_CLOSE: "Salir",
    BUTTON_SUBMIT: "Analizar",
    IMG_CHARLES: "https://cdn11.bigcommerce.com/s-csqcv5l47s/images/stencil/original/products/1955/4171/Marvel_ProfessorX_Bust_01__34435.1639005122__18434.1680639623.jpg?c=1",
}
